
- link:
    ~/.config/fish:
        path: config/fish
        create: true
        force: true

- shell:
    - omf install keychain
    - omf install z
    - omf install dangerous
    - omf install gityaw
