#!/usr/bin/env bash

# TODO: bundle into omf plugin

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

NVM_DIR=$HOME/.nvm

. $NVM_DIR/nvm.sh; npm install -g $(cat config/npm/packages)
